### ISSUE TITLE
DarkMode for projects

### ISSUE THREAD

**Issue by morektz** [buildspace/buildspace-projects#631]
Is it possible to implement a darkmode ? for the projects ? at the moment its really bright when changing windows from vscode. 

As of now the projects page looks like this 
https://ibb.co/CHgvVGs

**Comment by adilanchian** [comment]
Hey @morektz -

Thanks for this :). We have dark mode in the backlog!! It's a highly requested feature for sure haha. Will be implementing most likely with a refresh of the web app.

Keep on eye out in the Discord :). Will keep this open to gauge interest on this for sure though!

**Comment by stufflebeam** [comment]
Hi friends!

I just wanted to chime in here and add my +1 to the issue, since it's been a while since this issue has seen an update. I'm currently working through one of the projects, and, like @morektz, I am finding it particularly jarring to jump back and forth between a dark editor window and the bright project site.

Has there been any progress on this since the issue was raised in December? Also, is the site/app itself open sourced somewhere else? If so, I'd be game to have a look to see what I can do to help.

I didn't do much deep recon in the code, but a quick look at the DOM leads me to believe that you all are using chakra UI for the styles on the site. If that's the case, depending on which implementation is being used, these links I found might prove helpful in adding a light/dark mode toggle to the site:

https://chakra-ui.com/docs/styled-system/features/color-mode

https://v0.chakra-ui.com/color-mode

Ok, well, I just wanted to see where things were on this at this point. 

Regardless of the status of this issue though, everything buildspace is simply fantastic! Thanks for all that you all do! 💚

**Comment by helloitsm3** [comment]
Closing this as this is outdated. Feel free to re-open it if the issue persists.
